### ISSUE TITLE
`completion` block of `scanForButtons` is never called on iOS 16 beta 3

### ISSUE THREAD

**Issue by stonko1994** [50ButtonsEach/flic2lib-ios#25] opened 2022-07-22 10:04 UTC
**Environment:**
- iPhone 13 Pro Max
- iOS 16.0 developer beta 3

When scanning for buttons using the `FLICManager#scanForButtons` the `completion` block will never be called. However, the `stateChangeHandler` is called as expected with the expected `.discovered` value.
_There is also no 'pairing alert' popping up when running on iOS 16 beta 3._

I did ensure that:
- `FLICManager.configure` is called first
- the state of the manager is `poweredOn`

_The same code works fine on `iOS 15.5`._

**Comment by sennah911** [comment] 2022-07-27 09:58
We are seeing the same behaviour. We get a `.discovered` event. And nothing more.

The button appears happy with the connection, with the led going green when pressed, but no way of setting a delegate for it since it does not appear in `FLICManager.shared()?.buttons()` or the completion block.

If we try to pair again with the same button, sometimes we get a completion with error 10.

**Comment by Emill** [comment] 2022-07-27 11:44
Hi. We will investigate this shortly. Might be some undocumented behaviour change in iOS that causes this.

**Comment by sennah911** [comment] 2022-08-01 14:26
Dev beta 3 is the only one I've tested. (I have yet to try on beta 4...)

**Comment by Emill** [comment] 2022-08-01 14:48
Ok so we filed a bug report to Apple. Hopefully they will respond and fix the issue...
What happens is that the device connects, but iOS's Bluetooth stack never delivers the `didConnectPeripheral` event to the app.

**Comment by stonko1994** [comment] 2022-08-02 06:56
> Have any of you by chance tested an earlier iOS 16 beta, to see if it works/not works there?

IIRC it did work for me in beta 1. I created the project I'm working on with Xcode 14 already and initially, it worked fine. (Had to change the deployment target to 15.5 in order to test it again 😓)

---

The same still happens on beta 4.

**Comment by ezzmoaz** [comment] 2022-08-08 22:21
> Ok so we filed a bug report to Apple. Hopefully they will respond and fix the issue...
> What happens is that the device connects, but iOS's Bluetooth stack never delivers the `didConnectPeripheral` event to the app.

I am getting the same behaviour on iOS 16 public beta 1
**Observation:**
I have another implantation on the same project that uses `CoreBluetooth` directly with another type of Bluetooth button and it is receiving `didConnectPeripheral` event.

**Comment by Emill** [comment] 2022-08-08 23:07
There are some factors that cause this bug. First, only Bluetooth 5 and later peripherals seem to be affected. These newer versions of Bluetooth support different PHYs and the LE Data Length Extension. It seems to be the negotiation of these features where Apple have messed up their state management. If PHY negotiation happens to complete after Data Length negotiation, everything is fine, but if PHY negotiation completes before Data Length negotiation completes, Apple's Bluetooth stack hangs and get stuck.

Therefore, Flic 1 for example, which is using Bluetooth 4.0, works fine.

**Comment by ezzmoaz** [comment] 2022-08-08 23:16
> There are some factors that cause this bug. First, only Bluetooth 5 and later peripherals seem to be affected. These newer versions of Bluetooth support different PHYs and the LE Data Length Extension. It seems to be the negotiation of these features where Apple have messed up their state management. If PHY negotiation happens to complete after Data Length negotiation, everything is fine, but if PHY negotiation completes before Data Length negotiation completes, Apple's Bluetooth stack hangs and get stuck.
> 
> Therefore, Flic 1 for example, which is using Bluetooth 4.0, works fine.

Thanks for the clarification and for the quick reply. Waiting for more updates when they become available 😃

**Comment by stonko1994** [comment] 2022-08-09 09:00
It works again for me on iOS 16 beta 5 🥳

@Emill feel free to close the issue once you or anyone else can confirm this.

**Comment by sennah911** [comment] 2022-08-09 10:49
I can confirm, it is working for me too on beta 5.

**Comment by Emill** [comment] 2022-08-09 13:01
Seems fixed for us too on developer beta 5, so closing this issue.

**Closed by Emill** 2022-08-09 13:01 UTC
